from __future__ import annotations

import base64
import json
import logging
from typing import Optional

logger = logging.getLogger(__name__)


class GiteaClient:
    """Async Gitea API v1 client. Requires httpx."""

    def __init__(self, base_url: str, token: str) -> None:
        self.base_url = base_url.rstrip("/")
        self._headers = {
            "Authorization": f"token {token}",
            "Content-Type": "application/json",
        }

    async def push_files(
        self,
        owner: str,
        repo_name: str,
        files: dict[str, str],
        branch: str = "main",
    ) -> str:
        """Ensure repo exists, push all files, return repo HTML URL."""
        import httpx
        async with httpx.AsyncClient(headers=self._headers, timeout=30.0) as client:
            repo_url = await self._ensure_repo(client, owner, repo_name)
            for filepath, content in files.items():
                await self._upsert_file(client, owner, repo_name, filepath, content, branch)
        return repo_url

    async def _ensure_repo(self, client, owner: str, repo_name: str) -> str:
        r = await client.get(f"{self.base_url}/api/v1/repos/{owner}/{repo_name}")
        if r.status_code == 200:
            return r.json()["html_url"]
        r = await client.post(
            f"{self.base_url}/api/v1/user/repos",
            content=json.dumps({
                "name": repo_name,
                "description": "Generated by VibeForge AI",
                "private": True,
                "auto_init": True,
                "default_branch": "main",
            }),
        )
        r.raise_for_status()
        return r.json()["html_url"]

    async def _upsert_file(
        self, client, owner: str, repo_name: str,
        filepath: str, content: str, branch: str,
    ) -> None:
        encoded = base64.b64encode(content.encode()).decode()
        url = f"{self.base_url}/api/v1/repos/{owner}/{repo_name}/contents/{filepath}"
        r = await client.get(url, params={"ref": branch})
        if r.status_code == 200:
            sha = r.json()["sha"]
            payload = {"message": "chore: update via VibeForge AI",
                       "content": encoded, "sha": sha, "branch": branch}
        else:
            payload = {"message": "feat: add via VibeForge AI",
                       "content": encoded, "branch": branch}
        r = await client.put(url, content=json.dumps(payload))
        r.raise_for_status()


def build_gitea_client() -> Optional[GiteaClient]:
    """Build from GITEA_BASE_URL + GITEA_TOKEN env vars, or None."""
    import os
    base_url = os.environ.get("GITEA_BASE_URL", "").strip()
    token    = os.environ.get("GITEA_TOKEN", "").strip()
    if base_url and token:
        logger.info("[GiteaClient] configured — %s", base_url)
        return GiteaClient(base_url, token)
    logger.debug("[GiteaClient] not configured — stub URLs will be used")
    return None